package net.morilib.lingua;

import junit.framework.TestCase;

/**
 * 
 *
 *
 * @author MORIGUCHI, Yuichiro 2012/12/01
 */
public class JapaneseUtilsTest extends TestCase {

	public void testToRomaji1() {
		assertEquals(JapaneseUtils.toRomaji("アイウエオ", 0), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("カキクケコ", 0), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("サシスセソ", 0), "sashisuseso");
		assertEquals(JapaneseUtils.toRomaji("タチツテト", 0), "tachitsuteto");
		assertEquals(JapaneseUtils.toRomaji("ナニヌネノ", 0), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("ハヒフヘホ", 0), "hahifuheho");
		assertEquals(JapaneseUtils.toRomaji("マミムメモ", 0), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("ヤイユエヨ", 0), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("ラリルレロ", 0), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("ワヰウヱヲ", 0), "wawiuwewo");
		assertEquals(JapaneseUtils.toRomaji("ガギグゲゴ", 0), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ザジズゼゾ", 0), "zajizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ダヂヅデド", 0), "dajizudedo");
		assertEquals(JapaneseUtils.toRomaji("バビブベボ", 0), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("パピプペポ", 0), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("ンワヲン", 0), "nwawon");
		assertEquals(JapaneseUtils.toRomaji("キャキュキェキョ", 0), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("シャシュシェショ", 0), "shashushesho");
		assertEquals(JapaneseUtils.toRomaji("チャチュチェチョ", 0), "chachuchecho");
		assertEquals(JapaneseUtils.toRomaji("ニャニュニェニョ", 0), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ヒャヒュヒェヒョ", 0), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("ミャミュミェミョ", 0), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("リャリュリェリョ", 0), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("ギャギュギェギョ", 0), "gyagyugyegyo");
		assertEquals(JapaneseUtils.toRomaji("ジャジュジェジョ", 0), "jajujejo");
		assertEquals(JapaneseUtils.toRomaji("ビャビュビェビョ", 0), "byabyubyebyo");
		assertEquals(JapaneseUtils.toRomaji("ピャピュピェピョ", 0), "pyapyupyepyo");
		assertEquals(JapaneseUtils.toRomaji("イェス", 0), "yesu");
		assertEquals(JapaneseUtils.toRomaji("ウァウィウェウォ", 0), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ファフィフェフォ", 0), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("ツァツィツェツォ", 0), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("クァクィクェクォ", 0), "quaquiquequo");
		assertEquals(JapaneseUtils.toRomaji("グァグィグェグォ", 0), "gwagwigwegwo");
		assertEquals(JapaneseUtils.toRomaji("アース", 0), "asu");
		assertEquals(JapaneseUtils.toRomaji("オウジャノケン", 0), "ojanoken");
		assertEquals(JapaneseUtils.toRomaji("オオイマチ", 0), "oimachi");
		assertEquals(JapaneseUtils.toRomaji("ンジャメナ", 0), "njamena");
		assertEquals(JapaneseUtils.toRomaji("ティー", 0), "ti");
		assertEquals(JapaneseUtils.toRomaji("ディジタル", 0), "dijitaru");
		assertEquals(JapaneseUtils.toRomaji("ヴァヴィヴヴェヴォ", 0), "vavivuvevo");
		assertEquals(JapaneseUtils.toRomaji("ドッグ", 0), "doggu");
		assertEquals(JapaneseUtils.toRomaji("キャット", 0), "kyatto");
		assertEquals(JapaneseUtils.toRomaji("トゥハート", 0), "tuhato");
		assertEquals(JapaneseUtils.toRomaji("高町ヴィヴィオ", 0), "高町vivio");
		assertEquals(JapaneseUtils.toRomaji("ビビッドレッド", 0), "bibiddoreddo");
		assertEquals(JapaneseUtils.toRomaji("オペレーション", 0), "opereshon");
		assertEquals(JapaneseUtils.toRomaji("アキヅキリョウ", 0), "akizukiryo");
		assertEquals(JapaneseUtils.toRomaji("シンバシ", 0), "shimbashi");
		assertEquals(JapaneseUtils.toRomaji("タンマチ", 0), "tammachi");
		assertEquals(JapaneseUtils.toRomaji("カンピョウ", 0), "kampyo");
		assertEquals(JapaneseUtils.toRomaji("カンヨウ", 0), "kanyo");
		assertEquals(JapaneseUtils.toRomaji("デンエントシ", 0), "denentoshi");
		assertEquals(JapaneseUtils.toRomaji("イッチョウメ", 0), "itchome");
	}

	public void testToRomaji2() {
		assertEquals(JapaneseUtils.toRomaji("アイウエオ", 1), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("カキクケコ", 1), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("サシスセソ", 1), "sasisuseso");
		assertEquals(JapaneseUtils.toRomaji("タチツテト", 1), "tatituteto");
		assertEquals(JapaneseUtils.toRomaji("ナニヌネノ", 1), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("ハヒフヘホ", 1), "hahihuheho");
		assertEquals(JapaneseUtils.toRomaji("マミムメモ", 1), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("ヤイユエヨ", 1), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("ラリルレロ", 1), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("ワヰウヱヲ", 1), "waiueo");
		assertEquals(JapaneseUtils.toRomaji("ガギグゲゴ", 1), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ザジズゼゾ", 1), "zazizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ダヂヅデド", 1), "dazizudedo");
		assertEquals(JapaneseUtils.toRomaji("バビブベボ", 1), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("パピプペポ", 1), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("ンワヲン", 1), "nwaon");
		assertEquals(JapaneseUtils.toRomaji("キャキュキェキョ", 1), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("シャシュシェショ", 1), "syasyusyesyo");
		assertEquals(JapaneseUtils.toRomaji("チャチュチェチョ", 1), "tyatyutyetyo");
		assertEquals(JapaneseUtils.toRomaji("ニャニュニェニョ", 1), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ヒャヒュヒェヒョ", 1), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("ミャミュミェミョ", 1), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("リャリュリェリョ", 1), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("ギャギュギェギョ", 1), "gyagyugyegyo");
		assertEquals(JapaneseUtils.toRomaji("ジャジュジェジョ", 1), "zyazyuzyezyo");
		assertEquals(JapaneseUtils.toRomaji("ビャビュビェビョ", 1), "byabyubyebyo");
		assertEquals(JapaneseUtils.toRomaji("ピャピュピェピョ", 1), "pyapyupyepyo");
		assertEquals(JapaneseUtils.toRomaji("イェス", 1), "yesu");
		assertEquals(JapaneseUtils.toRomaji("ウァウィウェウォ", 1), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ファフィフェフォ", 1), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("ツァツィツェツォ", 1), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("クァクィクェクォ", 1), "kwakwikwekwo");
		assertEquals(JapaneseUtils.toRomaji("グァグィグェグォ", 1), "gwagwigwegwo");
		assertEquals(JapaneseUtils.toRomaji("アース", 1), "âsu");
		assertEquals(JapaneseUtils.toRomaji("オウジャノケン", 1), "ôzyanoken");
		assertEquals(JapaneseUtils.toRomaji("オオイマチ", 1), "ôimati");
		assertEquals(JapaneseUtils.toRomaji("ンジャメナ", 1), "nzyamena");
		assertEquals(JapaneseUtils.toRomaji("ティー", 1), "tî");
		assertEquals(JapaneseUtils.toRomaji("ディジタル", 1), "dizitaru");
		assertEquals(JapaneseUtils.toRomaji("ヴァヴィヴヴェヴォ", 1), "vavivuvevo");
		assertEquals(JapaneseUtils.toRomaji("ドッグ", 1), "doggu");
		assertEquals(JapaneseUtils.toRomaji("キャット", 1), "kyatto");
		assertEquals(JapaneseUtils.toRomaji("トゥハート", 1), "tuhâto");
		assertEquals(JapaneseUtils.toRomaji("高町ヴィヴィオ", 1), "高町vivio");
		assertEquals(JapaneseUtils.toRomaji("ビビッドレッド", 1), "bibiddoreddo");
		assertEquals(JapaneseUtils.toRomaji("オペレーション", 1), "operêsyon");
		assertEquals(JapaneseUtils.toRomaji("アキヅキリョウ", 1), "akizukiryô");
		assertEquals(JapaneseUtils.toRomaji("シンバシ", 1), "sinbasi");
		assertEquals(JapaneseUtils.toRomaji("タンマチ", 1), "tanmati");
		assertEquals(JapaneseUtils.toRomaji("カンピョウ", 1), "kanpyô");
		assertEquals(JapaneseUtils.toRomaji("カンヨウ", 1), "kan'yô");
		assertEquals(JapaneseUtils.toRomaji("デンエントシ", 1), "den'entosi");
		assertEquals(JapaneseUtils.toRomaji("イッチョウメ", 1), "ittyôme");
	}

	public void testToRomaji3() {
		assertEquals(JapaneseUtils.toRomaji("アイウエオ", 2), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("カキクケコ", 2), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("サシスセソ", 2), "sashisuseso");
		assertEquals(JapaneseUtils.toRomaji("タチツテト", 2), "tachitsuteto");
		assertEquals(JapaneseUtils.toRomaji("ナニヌネノ", 2), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("ハヒフヘホ", 2), "hahifuheho");
		assertEquals(JapaneseUtils.toRomaji("マミムメモ", 2), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("ヤイユエヨ", 2), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("ラリルレロ", 2), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("ワヰウヱヲ", 2), "wawiuwewo");
		assertEquals(JapaneseUtils.toRomaji("ガギグゲゴ", 2), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ザジズゼゾ", 2), "zajizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ダヂヅデド", 2), "dajidzudedo");
		assertEquals(JapaneseUtils.toRomaji("バビブベボ", 2), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("パピプペポ", 2), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("ンワヲン", 2), "nwawon");
		assertEquals(JapaneseUtils.toRomaji("キャキュキェキョ", 2), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("シャシュシェショ", 2), "shashushesho");
		assertEquals(JapaneseUtils.toRomaji("チャチュチェチョ", 2), "chachuchecho");
		assertEquals(JapaneseUtils.toRomaji("ニャニュニェニョ", 2), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ヒャヒュヒェヒョ", 2), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("ミャミュミェミョ", 2), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("リャリュリェリョ", 2), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("ギャギュギェギョ", 2), "gyagyugyegyo");
		assertEquals(JapaneseUtils.toRomaji("ジャジュジェジョ", 2), "jajujejo");
		assertEquals(JapaneseUtils.toRomaji("ビャビュビェビョ", 2), "byabyubyebyo");
		assertEquals(JapaneseUtils.toRomaji("ピャピュピェピョ", 2), "pyapyupyepyo");
		assertEquals(JapaneseUtils.toRomaji("イェス", 2), "yesu");
		assertEquals(JapaneseUtils.toRomaji("ウァウィウェウォ", 2), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ファフィフェフォ", 2), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("ツァツィツェツォ", 2), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("クァクィクェクォ", 2), "quaquiquequo");
		assertEquals(JapaneseUtils.toRomaji("グァグィグェグォ", 2), "gwagwigwegwo");
		assertEquals(JapaneseUtils.toRomaji("アース", 2), "asu");
		assertEquals(JapaneseUtils.toRomaji("オウジャノケン", 2), "ojanoken");
		assertEquals(JapaneseUtils.toRomaji("オオイマチ", 2), "oimachi");
		assertEquals(JapaneseUtils.toRomaji("ンジャメナ", 2), "njamena");
		assertEquals(JapaneseUtils.toRomaji("ティー", 2), "ti");
		assertEquals(JapaneseUtils.toRomaji("ディジタル", 2), "dijitaru");
		assertEquals(JapaneseUtils.toRomaji("ヴァヴィヴヴェヴォ", 2), "vavivuvevo");
		assertEquals(JapaneseUtils.toRomaji("ドッグ", 2), "doggu");
		assertEquals(JapaneseUtils.toRomaji("キャット", 2), "kyatto");
		assertEquals(JapaneseUtils.toRomaji("トゥハート", 2), "tuhato");
		assertEquals(JapaneseUtils.toRomaji("高町ヴィヴィオ", 2), "高町vivio");
		assertEquals(JapaneseUtils.toRomaji("ビビッドレッド", 2), "bibiddoreddo");
		assertEquals(JapaneseUtils.toRomaji("オペレーション", 2), "opereshon");
		assertEquals(JapaneseUtils.toRomaji("アキヅキリョウ", 2), "akidzukiryo");
		assertEquals(JapaneseUtils.toRomaji("シンバシ", 2), "shimbashi");
		assertEquals(JapaneseUtils.toRomaji("タンマチ", 2), "tammachi");
		assertEquals(JapaneseUtils.toRomaji("カンピョウ", 2), "kampyo");
		assertEquals(JapaneseUtils.toRomaji("カンヨウ", 2), "kanyo");
		assertEquals(JapaneseUtils.toRomaji("デンエントシ", 2), "denentoshi");
		assertEquals(JapaneseUtils.toRomaji("イッチョウメ", 2), "itchome");
	}

	public void testToRomaji4() {
		assertEquals(JapaneseUtils.toRomaji("アイウエオ", 4), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("カキクケコ", 4), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("サシスセソ", 4), "sashisuseso");
		assertEquals(JapaneseUtils.toRomaji("タチツテト", 4), "tachitsuteto");
		assertEquals(JapaneseUtils.toRomaji("ナニヌネノ", 4), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("ハヒフヘホ", 4), "hahifuheho");
		assertEquals(JapaneseUtils.toRomaji("マミムメモ", 4), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("ヤイユエヨ", 4), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("ラリルレロ", 4), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("ワヰウヱヲ", 4), "wawiuwewo");
		assertEquals(JapaneseUtils.toRomaji("ガギグゲゴ", 4), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ザジズゼゾ", 4), "zajizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ダヂヅデド", 4), "dajizudedo");
		assertEquals(JapaneseUtils.toRomaji("バビブベボ", 4), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("パピプペポ", 4), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("ンワヲン", 4), "nwawon");
		assertEquals(JapaneseUtils.toRomaji("キャキュキェキョ", 4), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("シャシュシェショ", 4), "shashushesho");
		assertEquals(JapaneseUtils.toRomaji("チャチュチェチョ", 4), "chachuchecho");
		assertEquals(JapaneseUtils.toRomaji("ニャニュニェニョ", 4), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ヒャヒュヒェヒョ", 4), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("ミャミュミェミョ", 4), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("リャリュリェリョ", 4), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("ギャギュギェギョ", 4), "gyagyugyegyo");
		assertEquals(JapaneseUtils.toRomaji("ジャジュジェジョ", 4), "jajujejo");
		assertEquals(JapaneseUtils.toRomaji("ビャビュビェビョ", 4), "byabyubyebyo");
		assertEquals(JapaneseUtils.toRomaji("ピャピュピェピョ", 4), "pyapyupyepyo");
		assertEquals(JapaneseUtils.toRomaji("イェス", 4), "yesu");
		assertEquals(JapaneseUtils.toRomaji("ウァウィウェウォ", 4), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ファフィフェフォ", 4), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("ツァツィツェツォ", 4), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("クァクィクェクォ", 4), "quaquiquequo");
		assertEquals(JapaneseUtils.toRomaji("グァグィグェグォ", 4), "gwagwigwegwo");
		assertEquals(JapaneseUtils.toRomaji("アース", 4), "ahsu");
		assertEquals(JapaneseUtils.toRomaji("オウジャノケン", 4), "ohjanoken");
		assertEquals(JapaneseUtils.toRomaji("オオイマチ", 4), "ohimachi");
		assertEquals(JapaneseUtils.toRomaji("ンジャメナ", 4), "njamena");
		assertEquals(JapaneseUtils.toRomaji("ティー", 4), "tih");
		assertEquals(JapaneseUtils.toRomaji("ディジタル", 4), "dijitaru");
		assertEquals(JapaneseUtils.toRomaji("ヴァヴィヴヴェヴォ", 4), "vavivuvevo");
		assertEquals(JapaneseUtils.toRomaji("ドッグ", 4), "doggu");
		assertEquals(JapaneseUtils.toRomaji("キャット", 4), "kyatto");
		assertEquals(JapaneseUtils.toRomaji("トゥハート", 4), "tuhahto");
		assertEquals(JapaneseUtils.toRomaji("高町ヴィヴィオ", 4), "高町vivio");
		assertEquals(JapaneseUtils.toRomaji("ビビッドレッド", 4), "bibiddoreddo");
		assertEquals(JapaneseUtils.toRomaji("オペレーション", 4), "operehshon");
		assertEquals(JapaneseUtils.toRomaji("アキヅキリョウ", 4), "akizukiryoh");
		assertEquals(JapaneseUtils.toRomaji("シンバシ", 4), "shimbashi");
		assertEquals(JapaneseUtils.toRomaji("タンマチ", 4), "tammachi");
		assertEquals(JapaneseUtils.toRomaji("カンピョウ", 4), "kampyoh");
		assertEquals(JapaneseUtils.toRomaji("カンヨウ", 4), "kanyoh");
		assertEquals(JapaneseUtils.toRomaji("デンエントシ", 4), "denentoshi");
		assertEquals(JapaneseUtils.toRomaji("イッチョウメ", 4), "itchohme");
	}

	public void testToRomaji5() {
		assertEquals(JapaneseUtils.toRomaji("アイウエオ", 8), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("カキクケコ", 8), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("サシスセソ", 8), "sashisuseso");
		assertEquals(JapaneseUtils.toRomaji("タチツテト", 8), "tachitsuteto");
		assertEquals(JapaneseUtils.toRomaji("ナニヌネノ", 8), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("ハヒフヘホ", 8), "hahifuheho");
		assertEquals(JapaneseUtils.toRomaji("マミムメモ", 8), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("ヤイユエヨ", 8), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("ラリルレロ", 8), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("ワヰウヱヲ", 8), "wawiuwewo");
		assertEquals(JapaneseUtils.toRomaji("ガギグゲゴ", 8), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ザジズゼゾ", 8), "zajizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ダヂヅデド", 8), "dajizudedo");
		assertEquals(JapaneseUtils.toRomaji("バビブベボ", 8), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("パピプペポ", 8), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("ンワヲン", 8), "nwawon");
		assertEquals(JapaneseUtils.toRomaji("キャキュキェキョ", 8), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("シャシュシェショ", 8), "shashushesho");
		assertEquals(JapaneseUtils.toRomaji("チャチュチェチョ", 8), "chachuchecho");
		assertEquals(JapaneseUtils.toRomaji("ニャニュニェニョ", 8), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ヒャヒュヒェヒョ", 8), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("ミャミュミェミョ", 8), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("リャリュリェリョ", 8), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("ギャギュギェギョ", 8), "gyagyugyegyo");
		assertEquals(JapaneseUtils.toRomaji("ジャジュジェジョ", 8), "jajujejo");
		assertEquals(JapaneseUtils.toRomaji("ビャビュビェビョ", 8), "byabyubyebyo");
		assertEquals(JapaneseUtils.toRomaji("ピャピュピェピョ", 8), "pyapyupyepyo");
		assertEquals(JapaneseUtils.toRomaji("イェス", 8), "yesu");
		assertEquals(JapaneseUtils.toRomaji("ウァウィウェウォ", 8), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ファフィフェフォ", 8), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("ツァツィツェツォ", 8), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("クァクィクェクォ", 8), "quaquiquequo");
		assertEquals(JapaneseUtils.toRomaji("グァグィグェグォ", 8), "gwagwigwegwo");
		assertEquals(JapaneseUtils.toRomaji("アース", 8), "āsu");
		assertEquals(JapaneseUtils.toRomaji("オウジャノケン", 8), "ōjanoken");
		assertEquals(JapaneseUtils.toRomaji("オオイマチ", 8), "ōimachi");
		assertEquals(JapaneseUtils.toRomaji("ンジャメナ", 8), "njamena");
		assertEquals(JapaneseUtils.toRomaji("ティー", 8), "tī");
		assertEquals(JapaneseUtils.toRomaji("ディジタル", 8), "dijitaru");
		assertEquals(JapaneseUtils.toRomaji("ヴァヴィヴヴェヴォ", 8), "vavivuvevo");
		assertEquals(JapaneseUtils.toRomaji("ドッグ", 8), "doggu");
		assertEquals(JapaneseUtils.toRomaji("キャット", 8), "kyatto");
		assertEquals(JapaneseUtils.toRomaji("トゥハート", 8), "tuhāto");
		assertEquals(JapaneseUtils.toRomaji("高町ヴィヴィオ", 8), "高町vivio");
		assertEquals(JapaneseUtils.toRomaji("ビビッドレッド", 8), "bibiddoreddo");
		assertEquals(JapaneseUtils.toRomaji("オペレーション", 8), "operēshon");
		assertEquals(JapaneseUtils.toRomaji("アキヅキリョウ", 8), "akizukiryō");
		assertEquals(JapaneseUtils.toRomaji("シンバシ", 8), "shimbashi");
		assertEquals(JapaneseUtils.toRomaji("タンマチ", 8), "tammachi");
		assertEquals(JapaneseUtils.toRomaji("カンピョウ", 8), "kampyō");
		assertEquals(JapaneseUtils.toRomaji("カンヨウ", 8), "kanyō");
		assertEquals(JapaneseUtils.toRomaji("デンエントシ", 8), "denentoshi");
		assertEquals(JapaneseUtils.toRomaji("イッチョウメ", 8), "itchōme");
	}

	public void testToRomaji6() {
		assertEquals(JapaneseUtils.toRomaji("アイウエオ", 128), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("カキクケコ", 128), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("サシスセソ", 128), "sashisuseso");
		assertEquals(JapaneseUtils.toRomaji("タチツテト", 128), "tachitsuteto");
		assertEquals(JapaneseUtils.toRomaji("ナニヌネノ", 128), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("ハヒフヘホ", 128), "hahifuheho");
		assertEquals(JapaneseUtils.toRomaji("マミムメモ", 128), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("ヤイユエヨ", 128), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("ラリルレロ", 128), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("ワヰウヱヲ", 128), "wawiuwewo");
		assertEquals(JapaneseUtils.toRomaji("ガギグゲゴ", 128), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ザジズゼゾ", 128), "zajizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ダヂヅデド", 128), "dajizudedo");
		assertEquals(JapaneseUtils.toRomaji("バビブベボ", 128), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("パピプペポ", 128), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("ンワヲン", 128), "nwawon");
		assertEquals(JapaneseUtils.toRomaji("キャキュキェキョ", 128), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("シャシュシェショ", 128), "shashushesho");
		assertEquals(JapaneseUtils.toRomaji("チャチュチェチョ", 128), "chachuchecho");
		assertEquals(JapaneseUtils.toRomaji("ニャニュニェニョ", 128), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ヒャヒュヒェヒョ", 128), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("ミャミュミェミョ", 128), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("リャリュリェリョ", 128), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("ギャギュギェギョ", 128), "gyagyugyegyo");
		assertEquals(JapaneseUtils.toRomaji("ジャジュジェジョ", 128), "jajujejo");
		assertEquals(JapaneseUtils.toRomaji("ビャビュビェビョ", 128), "byabyubyebyo");
		assertEquals(JapaneseUtils.toRomaji("ピャピュピェピョ", 128), "pyapyupyepyo");
		assertEquals(JapaneseUtils.toRomaji("イェス", 128), "yesu");
		assertEquals(JapaneseUtils.toRomaji("ウァウィウェウォ", 128), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ファフィフェフォ", 128), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("ツァツィツェツォ", 128), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("クァクィクェクォ", 128), "quaquiquequo");
		assertEquals(JapaneseUtils.toRomaji("グァグィグェグォ", 128), "gwagwigwegwo");
		assertEquals(JapaneseUtils.toRomaji("アース", 128), "asu");
		assertEquals(JapaneseUtils.toRomaji("オウジャノケン", 128), "ojanoken");
		assertEquals(JapaneseUtils.toRomaji("オオイマチ", 128), "oimachi");
		assertEquals(JapaneseUtils.toRomaji("ンジャメナ", 128), "njamena");
		assertEquals(JapaneseUtils.toRomaji("ティー", 128), "ti");
		assertEquals(JapaneseUtils.toRomaji("ディジタル", 128), "dijitaru");
		assertEquals(JapaneseUtils.toRomaji("ヴァヴィヴヴェヴォ", 128), "vavivuvevo");
		assertEquals(JapaneseUtils.toRomaji("ドッグ", 128), "doggu");
		assertEquals(JapaneseUtils.toRomaji("キャット", 128), "kyatto");
		assertEquals(JapaneseUtils.toRomaji("トゥハート", 128), "tuhato");
		assertEquals(JapaneseUtils.toRomaji("高町ヴィヴィオ", 128), "高町vivio");
		assertEquals(JapaneseUtils.toRomaji("ビビッドレッド", 128), "bibiddoreddo");
		assertEquals(JapaneseUtils.toRomaji("オペレーション", 128), "opereshon");
		assertEquals(JapaneseUtils.toRomaji("アキヅキリョウ", 128), "akizukiryo");
		assertEquals(JapaneseUtils.toRomaji("シンバシ", 128), "shimbashi");
		assertEquals(JapaneseUtils.toRomaji("タンマチ", 128), "tammachi");
		assertEquals(JapaneseUtils.toRomaji("カンピョウ", 128), "kampyo");
		assertEquals(JapaneseUtils.toRomaji("カンヨウ", 128), "kan-yo");
		assertEquals(JapaneseUtils.toRomaji("デンエントシ", 128), "den-entoshi");
		assertEquals(JapaneseUtils.toRomaji("イッチョウメ", 128), "itchome");
	}

	public void testToKatakana() {
		assertEquals(JapaneseUtils._katakana("あいうえお"), "アイウエオ");
		assertEquals(JapaneseUtils._katakana("かきくけこ"), "カキクケコ");
		assertEquals(JapaneseUtils._katakana("さしすせそ"), "サシスセソ");
		assertEquals(JapaneseUtils._katakana("たちつてと"), "タチツテト");
		assertEquals(JapaneseUtils._katakana("なにぬねの"), "ナニヌネノ");
		assertEquals(JapaneseUtils._katakana("はひふへほ"), "ハヒフヘホ");
		assertEquals(JapaneseUtils._katakana("まみむめも"), "マミムメモ");
		assertEquals(JapaneseUtils._katakana("やいゆえよ"), "ヤイユエヨ");
		assertEquals(JapaneseUtils._katakana("らりるれろ"), "ラリルレロ");
		assertEquals(JapaneseUtils._katakana("わゐうゑを"), "ワヰウヱヲ");
		assertEquals(JapaneseUtils._katakana("がぎぐげご"), "ガギグゲゴ");
		assertEquals(JapaneseUtils._katakana("ざじずぜぞ"), "ザジズゼゾ");
		assertEquals(JapaneseUtils._katakana("ばびぶべぼ"), "バビブベボ");
		assertEquals(JapaneseUtils._katakana("ぱぴぷぺぽ"), "パピプペポ");
		assertEquals(JapaneseUtils._katakana("ん"), "ン");
		assertEquals(JapaneseUtils._katakana("ぁぃぅぇぉゃゅょゎ"), "ァィゥェォャュョヮ");
	}

	public void testToRomajiHiragana1() {
		assertEquals(JapaneseUtils.toRomaji("あいうえお", 0), "aiueo");
		assertEquals(JapaneseUtils.toRomaji("かきくけこ", 0), "kakikukeko");
		assertEquals(JapaneseUtils.toRomaji("さしすせそ", 0), "sashisuseso");
		assertEquals(JapaneseUtils.toRomaji("たちつてと", 0), "tachitsuteto");
		assertEquals(JapaneseUtils.toRomaji("なにぬねの", 0), "naninuneno");
		assertEquals(JapaneseUtils.toRomaji("はひふへほ", 0), "hahifuheho");
		assertEquals(JapaneseUtils.toRomaji("まみむめも", 0), "mamimumemo");
		assertEquals(JapaneseUtils.toRomaji("やいゆえよ", 0), "yaiyueyo");
		assertEquals(JapaneseUtils.toRomaji("らりるれろ", 0), "rarirurero");
		assertEquals(JapaneseUtils.toRomaji("わゐうゑを", 0), "wawiuwewo");
		assertEquals(JapaneseUtils.toRomaji("がぎぐげご", 0), "gagigugego");
		assertEquals(JapaneseUtils.toRomaji("ざじずぜぞ", 0), "zajizuzezo");
		assertEquals(JapaneseUtils.toRomaji("ばびぶべぼ", 0), "babibubebo");
		assertEquals(JapaneseUtils.toRomaji("ぱぴぷぺぽ", 0), "papipupepo");
		assertEquals(JapaneseUtils.toRomaji("んわをん", 0), "nwawon");
		assertEquals(JapaneseUtils.toRomaji("きゃきゅきぇきょ", 0), "kyakyukyekyo");
		assertEquals(JapaneseUtils.toRomaji("しゃしゅしぇしょ", 0), "shashushesho");
		assertEquals(JapaneseUtils.toRomaji("ちゃちゅちぇちょ", 0), "chachuchecho");
		assertEquals(JapaneseUtils.toRomaji("にゃにゅにぇにょ", 0), "nyanyunyenyo");
		assertEquals(JapaneseUtils.toRomaji("ひゃひゅひぇひょ", 0), "hyahyuhyehyo");
		assertEquals(JapaneseUtils.toRomaji("みゃみゅみぇみょ", 0), "myamyumyemyo");
		assertEquals(JapaneseUtils.toRomaji("りゃりゅりぇりょ", 0), "ryaryuryeryo");
		assertEquals(JapaneseUtils.toRomaji("いぇす", 0), "yesu");
		assertEquals(JapaneseUtils.toRomaji("うぁうぃうぇうぉ", 0), "wawiwewo");
		assertEquals(JapaneseUtils.toRomaji("ふぁふぃふぇふぉ", 0), "fafifefo");
		assertEquals(JapaneseUtils.toRomaji("つぁつぃつぇつぉ", 0), "tsatsitsetso");
		assertEquals(JapaneseUtils.toRomaji("あーす", 0), "asu");
		assertEquals(JapaneseUtils.toRomaji("おうじゃのけん", 0), "ojanoken");
		assertEquals(JapaneseUtils.toRomaji("おおいまち", 0), "oimachi");
		assertEquals(JapaneseUtils.toRomaji("んじゃめな", 0), "njamena");
		assertEquals(JapaneseUtils.toRomaji("てぃー", 0), "ti");
		assertEquals(JapaneseUtils.toRomaji("でぃじたる", 0), "dijitaru");
	}

	public void testToKatakana1() {
		assertEquals(JapaneseUtils.toKatakana("aiueo", false), "アイウエオ");
		assertEquals(JapaneseUtils.toKatakana("kakikukeko", false), "カキクケコ");
		assertEquals(JapaneseUtils.toKatakana("sasisuseso", false), "サスィスセソ");
		assertEquals(JapaneseUtils.toKatakana("tatituteto", false), "タティトゥテト");
		assertEquals(JapaneseUtils.toKatakana("naninuneno", false), "ナニヌネノ");
		assertEquals(JapaneseUtils.toKatakana("hahifuheho", false), "ハヒフヘホ");
		assertEquals(JapaneseUtils.toKatakana("mamimumemo", false), "マミムメモ");
		assertEquals(JapaneseUtils.toKatakana("yayiyuyeyo", false), "ヤイユイェヨ");
		assertEquals(JapaneseUtils.toKatakana("rarirurero", false), "ラリルレロ");
		assertEquals(JapaneseUtils.toKatakana("wawiuwewo", false), "ワウィウウェウォ");
		assertEquals(JapaneseUtils.toKatakana("gagigugego", false), "ガギグゲゴ");
		assertEquals(JapaneseUtils.toKatakana("zazizuzezo", false), "ザズィズゼゾ");
		assertEquals(JapaneseUtils.toKatakana("dadidudedo", false), "ダディドゥデド");
		assertEquals(JapaneseUtils.toKatakana("babibubebo", false), "バビブベボ");
		assertEquals(JapaneseUtils.toKatakana("papipupepo", false), "パピプペポ");
		assertEquals(JapaneseUtils.toKatakana("nwawon", false), "ンワウォン");
		assertEquals(JapaneseUtils.toKatakana("kyakyukyekyo", false), "キャキュキェキョ");
		assertEquals(JapaneseUtils.toKatakana("shashishushesho", false), "シャシシュシェショ");
		assertEquals(JapaneseUtils.toKatakana("chachichuchecho", false), "チャチチュチェチョ");
		assertEquals(JapaneseUtils.toKatakana("nyanyunyenyo", false), "ニャニュニェニョ");
		assertEquals(JapaneseUtils.toKatakana("hyahyuhyehyo", false), "ヒャヒュヒェヒョ");
		assertEquals(JapaneseUtils.toKatakana("myamyumyemyo", false), "ミャミュミェミョ");
		assertEquals(JapaneseUtils.toKatakana("ryaryuryeryo", false), "リャリュリェリョ");
		assertEquals(JapaneseUtils.toKatakana("gyagyugyegyo", false), "ギャギュギェギョ");
		assertEquals(JapaneseUtils.toKatakana("jajijujejo", false), "ジャジジュジェジョ");
		assertEquals(JapaneseUtils.toKatakana("jyajyujyejyo", false), "ジャジュジェジョ");
		assertEquals(JapaneseUtils.toKatakana("byabyubyebyo", false), "ビャビュビェビョ");
		assertEquals(JapaneseUtils.toKatakana("pyapyupyepyo", false), "ピャピュピェピョ");
		assertEquals(JapaneseUtils.toKatakana("wawiwuwewo", false), "ワウィウウェウォ");
		assertEquals(JapaneseUtils.toKatakana("fafifufefo", false), "ファフィフフェフォ");
		assertEquals(JapaneseUtils.toKatakana("tsatsitsutsetso", false), "ツァツィツツェツォ");
		assertEquals(JapaneseUtils.toKatakana("quaquiquequo", false), "クァクィクェクォ");
		assertEquals(JapaneseUtils.toKatakana("kwakwikwekwo", false), "クァクィクェクォ");
		assertEquals(JapaneseUtils.toKatakana("gwagwigwegwo", false), "グァグィグェグォ");
	}

}
